In [9]:
import pandas as pd
import datetime

from finance_app import *

In [20]:
# Let's make a date range for each month/week:
weeks = pd.date_range('9/6/16', datetime.date.today(), freq='W' )

In [23]:
# What we want, but with automatically generated dates
df['9/6/16':'9/12/16']

,Description,Original Description,Amount,Transaction Type,Category,Account Name,Labels,Notes
Date,,,,,,,,
2016-09-12,Inst Xfer - Evernote,PAYPAL INST XFER 160909,69.99,debit,Electronics & Software,Investor Checking,NaN,NaN
2016-09-12,Jimmy John's,"JIMMY JOHNS # 9001ANN ARBOR, MI #0000001",8.20,debit,Restaurants,Investor Checking,NaN,NaN
2016-09-12,Panera Bread,"PANERA BREAD #6013ANN ARBOR, MI #0000001",5.82,debit,Fast Food,Investor Checking,NaN,NaN
2016-09-11,iTunes,"APL* ITUNES.COM/BI866-712-7753, CA #0000",8.47,debit,Music,Investor Checking,NaN,NaN
2016-09-11,7-Eleven,7-ELEVEN 1300 S UNIVERS ANN ARBOR,4.89,debit,Fast Food,Investor Checking,NaN,NaN
2016-09-10,Chane Music Ci,"CHANE MUSIC AND CI800-992-7252, FL #0000",124.25,debit,Electronics & Software,Investor Checking,NaN,NaN
2016-09-09,Mujo Cafe,"MUJO'S CAFE ANN ARBOR, MI #0000001",5.50,debit,Coffee Shops,Investor Checking,NaN,NaN
2016-09-08,Deposit Pncbank Xtransfr,ACH Deposit PNCBANK_XTRANSFR P2P,434.00,credit,Income,Campus Card Student Checking,NaN,NaN
2016-09-08,Penn Station Plymouth,"PENN STATION 268 PLYMOUTH, MI #00000019",12.16,debit,Fast Food,Investor Checking,NaN,NaN
2016-09-08,Planet Rock,"PLANET ROCK ANN ARBOR, MI #0000001",243.00,debit,Sports,Investor Checking,NaN,NaN
2016-09-08,Inst Xfer - IM leagues,PAYPAL INST XFER 160907,50.00,debit,Sports,Investor Checking,NaN,NaN
2016-09-07,Prime Student Ho - chriss,Prime Student Ho RESIDENT,739.00,debit,Mortgage & Rent,Investor Checking,Reimbursable,NaN
2016-09-07,Prime Student Ho,Prime Student Ho RESIDENT,738.95,debit,Mortgage & Rent,Investor Checking,NaN,NaN
2016-09-07,Mujo Cafe,"MUJO'S CAFE ANN ARBOR, MI #0000001",1.05,debit,Coffee Shops,Investor Checking,NaN,NaN
2016-09-07,Airbnb Payments G,AIRBNB PAYMENTS G4AAJOQM4P RMR*IK*G-52E,0.01,credit,Income,Investor Checking,NaN,NaN
2016-09-06,Ku Parking Web,"KU - PARKING WEB 785-864-5961, KS #0000",25.00,debit,Auto & Transport,Investor Checking,NaN,NaN
2016-09-06,Sublette Crct Cour,"SUBLETTE CRCT COUR307-367-2556, WY #0000",99.00,debit,Auto & Transport,Investor Checking,NaN,NaN
2016-09-06,Altairglob Cwf Altair,AltairGlob640CWF Altair,1269.00,credit,Income,Investor Checking,NaN,NaN
2016-09-06,Funds Transfer Brokerage,Funds Transfer from Brokerage -9258,7000.00,credit,Transfer,Investor Checking,Hide,NaN
2016-09-06,Funds Transfer Brokerage,Funds Transfer to Brokerage -9258,700.00,debit,Transfer,Investor Checking,Hide,NaN

In [19]:
df[months[0]:months[1]]

Empty DataFrame
Columns: [Description, Original Description, Amount, Transaction Type, Category, Account Name, Labels, Notes]
Index: []