In [217]:
# Summary: about $350 out of pocket, total expenses $1050 when incl $250 airbnb
sf_expenses.append(pd.Series(sf_expenses.sum(), name='total'))

           Expenses
food          73.55
coffee        35.86
transport    136.30
travel       416.58
drinks        42.43
shopping      39.56
misc          63.28
total        807.56

In [57]:
import pandas as pd
import datetime as dt
import re
%matplotlib inline

In [155]:
# Read in main
df = pd.read_csv('transactions.csv', parse_dates=['Date'], index_col = 'Date').truncate(after='10/1/2016')

In [156]:
# Need to find flights, from a few weeks back (Category:=Air Travel in October)
flights = df[df.Category=='Air Travel'];

In [157]:
# Begin and End date
sf = df.truncate(after = '10/23/16')
sf = sf.truncate(before = '10/28/16')
sf = pd.concat([sf,flights]) # Combine
null_labels = ['Hide']; null_cats = ['Utilities','Hide from Budgets & Trends']
sf = sf[~(sf.Category.isin(null_cats)|(sf.Labels.isin(null_labels)))]

In [158]:
# Instead of using df[~df.Cat.isin(List)], to use regexp need pattern and str.contains
null_descr = ['iTunes','Airbnb*', 'Mighty Good','Jimmy John\'s','Mujo*', 'Continental', 'Panch*']
pat_null_descr = '|'.join(null_descr)
sf = sf[~sf.Description.str.contains(pat_null_descr)] # winner

In [159]:
sf

,Description,Original Description,Amount,Transaction Type,Category,Account Name,Labels,Notes
Date,,,,,,,,
2016-10-28,Lyft - from airport,"LYFT *RIDE THU 6AM SAN FRANCISCO, CA, US on 10...",36.82,debit,Rental Car & Taxi,Investor Checking,NaN,NaN
2016-10-28,Venmo - Chris (sushi dinner),VENMO PAYMENT,20.00,debit,Auto & Transport,Investor Checking,NaN,NaN
2016-10-28,Venmo - Chris (drinks),VENMO PAYMENT,15.27,debit,Alcohol & Bars,Investor Checking,NaN,NaN
2016-10-28,"Venmo - Chris (parking, gas)",VENMO PAYMENT,15.00,debit,Auto & Transport,Investor Checking,NaN,NaN
2016-10-27,Cafeto Coffee,"SQ *CAFETO COFFEE San Francisco, CA #000",8.59,debit,Coffee Shops,Investor Checking,NaN,NaN
2016-10-27,Blue Bottle Cosan,"SQ *BLUE BOTTLE COSan Francisco, CA #000",10.92,debit,Coffee Shops,Investor Checking,NaN,NaN
2016-10-27,Lyft,"LYFT *RIDE WED 3LYFT.COM, CA #00000019",4.40,debit,Rental Car & Taxi,Investor Checking,NaN,NaN
2016-10-27,"San Francisco, Ca Rgnl","TEETH SAN FRANCISCO, CA #000",27.16,debit,Alcohol & Bars,Investor Checking,NaN,NaN
2016-10-27,Venmo - dinner to erik,VENMO PAYMENT,20.00,debit,Restaurants,Investor Checking,NaN,NaN
2016-10-27,BART,BART-CLIPPER GLEN PARK SAN FRANCISCO,7.40,debit,Public Transportation,Investor Checking,NaN,NaN
2016-10-26,Venmo - Dinner,VENMO PAYMENT ~ Tran: ACHDW,10.00,debit,Food & Dining,Investor Checking,NaN,NaN
2016-10-26,Lyft,"LYFT *RIDE MON 1LYFT.COM, CA #00000019",12.98,debit,Rental Car & Taxi,Investor Checking,NaN,NaN
2016-10-26,Working Girls Cafe,"WORKING GIRLS CAFESAN FRANCISCO, CA #000",10.82,debit,Restaurants,Investor Checking,NaN,NaN
2016-10-26,Federal Express,"FEDEXOFFICE 0005SAN FRANCISCO, CA #000",63.28,debit,Printing,Investor Checking,NaN,NaN
2016-10-26,Cafeto Coffee,"SQ *CAFETO COFFEE San Francisco, CA #000",8.50,debit,Coffee Shops,Investor Checking,NaN,NaN
2016-10-26,Venmo - Sushi,VENMO PAYMENT,19.94,debit,Food & Dining,Investor Checking,NaN,NaN
2016-10-25,H&M,"H&M #249 SAN MATEO, CA #0000001",39.56,debit,Clothing,Investor Checking,NaN,NaN
2016-10-25,Sightglass Cof,"SQ *SIGHTGLASS COFSan Francisco, CA #000",7.85,debit,Coffee Shops,Investor Checking,NaN,NaN
2016-10-25,Venmo Cashout - Mom/Dad Trip to SF,VENMO CASHOUT,700.00,credit,Income,Investor Checking,NaN,NaN
2016-10-24,Pizza House,"PIZZA HOUSE-GARAGEANN ARBOR, MI #0000001",12.79,debit,Fast Food,Investor Checking,NaN,NaN
2016-10-23,Greyhound,"GREYHOUND #4044 214-849-8966, TX #0000",26.00,debit,Auto & Transport,Investor Checking,NaN,NaN
2016-10-23,Uber.com,"UBER US OCT22 QEHELP.UBER.COM, CA #000",5.55,debit,Rental Car & Taxi,Investor Checking,NaN,NaN
2016-10-23,Uber.com,"UBER US OCT21 37HELP.UBER.COM, CA #000",8.15,debit,Rental Car & Taxi,Investor Checking,NaN,NaN
2016-10-21,Delta,"DELTA AIR 006236DELTA.COM, CA #0000001",131.60,debit,Air Travel,Investor Checking,NaN,NaN
2016-10-21,American Airlines,"AMERICAN AIR001239FORT WORTH, TX #000000",263.10,debit,Air Travel,Investor Checking,NaN,NaN
2016-10-21,Travel Insurance P,"TRAVEL INSURANCE P800-729-6021, VA #0000",21.88,debit,Air Travel,Investor Checking,NaN,NaN

In [160]:
# Import categories
from finance_app import *
# if we need to unpack list_all_categories:
#    list(itertools.chain(*list_all_categories))
names = ['food','coffee','transport','travel','drinks','sport','shopping','entertainment','fees','misc','home','edu','income','airbnb income','hidden']

In [170]:
data = [sf.loc[sf.Category.isin(i)].Amount.sum() for i in list_all_categories]
data

[73.55000000000001,
 35.86,
 136.3,
 416.58000000000004,
 42.43,
 0,
 39.56,
 0,
 0,
 63.28,
 0,
 0,
 700.0,
 0,
 0]

In [196]:
# Create Report of Categories
sf_report = pd.DataFrame(data=data, index=names, columns = ['Expenses'])
sf_report = sf_report[sf_report.Expenses>0];
# Separate income from expenses
sf_income = sf_report[-1:]; sf_expenses = sf_report[:-1];
# Return the Difference 
sf_income.sum() - sf_expenses.sum()

Expenses   -107.56
dtype: float64